### PR TITLE
Fix style generation

### LINKED ISSUE #116: For standard packages styles are generated outside of the `src` directory
**Bug** 

The latest change to support the package structure of widgets has caused issues generating styles for packages with the standard structure. The styles directory is built outside of the `src` directory.

### PR DESCRIPTION
**Pull request by bitpshr**
**Type:** bug / feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [ ] Unit or Functional tests are included in the PR

**Description:**

This PR resolves an issue where CSS files were being placed in the wrong directory for projects with a standard structure.

Resolves #116

### CODE REVIEW

File: tasks/util/postcss.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+
+export function createProcessors(dest: string, cwd = '', dist?: boolean) {
+	return [
+		postCssImport,
+		postCssNext({
+			features: {
+				autoprefixer: {
+					browsers: [
+						'last 2 versions',
+						'ie >= 10'
```
Comment (agubler) [inline tasks/util/postcss.ts]: curious, should this be 11 now? (i know not directly related with change)

Comment (bitpshr) [inline tasks/util/postcss.ts]: Yup, fixed.
